name: example

paths:
    # Add below the directory of the project.
    # Rest of the paths are relative but might need to be changed for specific cases.
    project: &projectpath /Users/Georg022/PycharmProjects/CS_Fisher
    output:
        fisher_matrix: !join [*projectpath, output]
        figures: !join [*projectpath, figures]

validation: [w0, wa]

cosmology:
    Omega_m: 0.315
    Omega_b: 0.049
    h: 0.674
    sigma8: 0.811
    n_s: 0.965
    w0: -1
    wa: 0

IA:
    A_IA: 1.0

step_size:
    Omega_m: 0.01
    Omega_b:
    h:
    sigma8: 0.05
    n_s:
    w0: 0.07
    wa: 0.3
    A_IA: 0.01
    delta_z: 0.02

ell_binning:
    cosmic_shear:
        bin_start: 20
        bin_end: 15001
        N_bins: 20
        ell_min: 100
        ell_max: 2000

forecast:
    fsky: 0.43
    e_rms: 0.26
    year: 10
    z_min: 0.1
    z_max: 4.
    N_z_values: 400
